groq:
  api_key: "..." 

llm:
  # model_name: "llama3-groq-70b-8192-tool-use-preview" # Shutdown Date 1/6/25 
  model_name: "llama-3.3-70b-versatile" # Recommended Replacement Model ID

rag:
  knowledge_base_dir: "data/knowledge_base/"

huggingface:
  access_token: "..." 